In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


##introduction to tensors
###Tensor is a multidimensional array

In [ ]:
#Scaler - scalar is a single number
scaler = torch.tensor(7) #creating a tensor
scaler


tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item() # get tensor back as python int

7

In [ ]:
#vector - vector is a single dimension tensor but can contain many numbers
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [ ]:
#Why random tensors?

#Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data


##Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [ ]:
#Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.ndim

(tensor([[0.8418, 0.1561, 0.7627, 0.0954],
         [0.9916, 0.5401, 0.6281, 0.7545],
         [0.7916, 0.3947, 0.0104, 0.8578]]),
 2)

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones

In [ ]:
#Creating a tensor of all zeroes
Zeroes = torch.zeros(size=(3,4))
Zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
Zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Creating a tensor of all ones
Ones = torch.ones(3,4)
Ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
Ones*Zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
Ones.dtype

torch.float32

##Creating a range based tensor

In [ ]:
# range based tensor using torch.arange()
range_based = torch.arange(3,18,5)
range_based

tensor([ 3,  8, 13])

In [ ]:
#Creating tensor like
ten_zeroes = torch.zeros_like(input=range_based)
ten_zeroes

tensor([0, 0, 0])

# Tensor dataTypes

#####Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

Tensors not right datatype,

Tensors not right shape,

Tensors not on the right device

In [ ]:
#float datatype
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # defaults to None, which is torch.float32 or whatever datatype is passed.
                               device=None, # defaults to None, what device is your tensor on.
                               requires_grad=False) # whether or not to track gradients with this tensor operation.

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

##Getting information from tensors (tensor attributes)
1.Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor, can use tensor.shape

3.Tensors not on the right device - to get device from a tensor, can use tensor.device

In [ ]:
some_tensor = torch.rand(4,8)
some_tensor

tensor([[0.8714, 0.1919, 0.9608, 0.7973, 0.5316, 0.3002, 0.4080, 0.3235],
        [0.6089, 0.5166, 0.9188, 0.4730, 0.9400, 0.5121, 0.8365, 0.3355],
        [0.3694, 0.8462, 0.3749, 0.1802, 0.8763, 0.0520, 0.1250, 0.6590],
        [0.2323, 0.0179, 0.2431, 0.7183, 0.3588, 0.9321, 0.8989, 0.7375]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8714, 0.1919, 0.9608, 0.7973, 0.5316, 0.3002, 0.4080, 0.3235],
        [0.6089, 0.5166, 0.9188, 0.4730, 0.9400, 0.5121, 0.8365, 0.3355],
        [0.3694, 0.8462, 0.3749, 0.1802, 0.8763, 0.0520, 0.1250, 0.6590],
        [0.2323, 0.0179, 0.2431, 0.7183, 0.3588, 0.9321, 0.8989, 0.7375]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 8])
Device tensor is on: cpu


#Manipulating Tensors (Tensor operations)

*Addition

*substraction

*multiplication(element wise)

*division

*matrix multiplication

In [ ]:
#create a tensor add addition operation
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor = tensor * 10 #tensor don't change unless they're reassigned.

In [ ]:
tensor*10

tensor([100, 200, 300])

In [ ]:
#try out pytorch in built function
torch.mul(tensor,10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor,10)

tensor([20, 30, 40])

##Two main ways of performing multiplication in neural networks and deep learning:

Element-wise multiplication

Matrix mutliplication (dot product)





In [ ]:
  #element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [ ]:
#matrix multiplication by hands
#using for loop is 10x slower than pytorch
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(1400)


##One of the most common errors in deep learning: shape errors


#####The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,2))

tensor([[1.0062, 0.2407],
        [0.5768, 0.1874],
        [0.7276, 0.1876]])

###One of the most common errors in deep learning: shape errors

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
#torch.mm(tensor_A,tensor_B) #torch.matmul is the same as torch.mm

#### To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

A **Transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B = tensor_B.T

In [ ]:
##The matrix multiplication operation works when tensor_B is transposed

In [ ]:
torch.mm(tensor_A,tensor_B), torch.mm(tensor_A,tensor_B).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([3, 2])

Multiplying: torch.Size([3, 2]) * torch.Size([3, 2]) <- inner dimensions match

Output:



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## Finding the minimum, maximum, sum, etc(Tensor aggregation)

In [ ]:
x = torch.arange(0,1000,10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [ ]:
torch.min(x), torch.max(x)

(tensor(0), tensor(990))

In [ ]:
x.min(), x.max() # same as above

(tensor(0), tensor(990))

In [ ]:
torch.mean(x.type(torch.float32))
# Find the mean - note: the torch.mean() function requires a tensor of float32

tensor(495.)

In [ ]:
x.type(torch.float32).mean() # same as above

tensor(495.)

In [ ]:
torch.sum(x), x.sum()

(tensor(49500), tensor(49500))

##### find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

In [ ]:
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(99)

###Reshaping, stacking, squeezing and unsqueezing tensors
*Reshaping - reshapes an input tensor to a defined shape

*View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

*Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

*Squeeze - removes all 1 dimensions from a tensor

*Unsqueeze - add a 1 dimension to a target tensor

*Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
#add an extra dimension - reshape
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# changes z changes x (becuase a view of a tensor shares the same memory as the original one)
z[:,0] = 5
z,x


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)  # dim = 1 for vertical stack
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0) # dim = 0 for horizontal stack
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# torch.squeeze() - remove all single dimensions from a target tensor

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a specific dimensons to a target tensor at a specific dim(dimenions)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
print("\n Unsqueezed: ")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

 Unsqueezed: 

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearrange the dimensions of a target tensor in a speicifed order
x_original = torch.rand(size=(224,224,3))

x_permuted = torch.permute(x_original,(2,0,1)) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


##Indexing- Selecting data from tensors

######Indexing with pyTorch is similar to indexing with numpy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# you can also use ":" to select "all" of a target dimension
print(x[:,0])
print(x[:,1])

tensor([[1, 2, 3]])
tensor([[4, 5, 6]])


In [ ]:
#Get all value of the 0 dimensions but only the 1 index value of 1st and 2nd dimension
x[:,1,1]



tensor([5])

In [ ]:
#Get index 0 of 0th & 1st dimension and all values of the 2nd dimensions
x[0,0,:]

tensor([1, 2, 3])

##PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)


PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

So, NumPy default type is float 64 and tensor default type is float 32

In [ ]:
# Change the array, keep the tensor
array = array + 2
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor * 2
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reporducibility - trying to take random out of random

##In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...



In [ ]:
torch.rand(3,3)

tensor([[0.3102, 0.2382, 0.4849],
        [0.0461, 0.3030, 0.4130],
        [0.4209, 0.4437, 0.7801]])

#To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.


#Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch
random_tensor_1 = torch.rand(3,4)
random_tensor_2 = torch.rand(3,4)
print(random_tensor_1)
print(random_tensor_2)
print(random_tensor_1 == random_tensor_2)

tensor([[0.4406, 0.9944, 0.8049, 0.1226],
        [0.5530, 0.7253, 0.9470, 0.9867],
        [0.6658, 0.4060, 0.6554, 0.4394]])
tensor([[0.3484, 0.2971, 0.0588, 0.6483],
        [0.3862, 0.7401, 0.4791, 0.7630],
        [0.3729, 0.7034, 0.2011, 0.8098]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
